# Generated by Django 5.2.4 on 2025-07-19 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0002_rename_genre_movie_genres"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="year",
            field=models.IntegerField(null=True),
        ),
    ]
