# Generated by Django 5.2.4 on 2025-07-19 21:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0004_book"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="country",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="movie",
            name="extra_data",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="movie",
            name="year",
            field=models.IntegerField(
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1888),
                    django.core.validators.MaxValueValidator(2025),
                ],
            ),
        ),
        migrations.AlterUniqueTogether(
            name="movie",
            unique_together={("title", "country", "year")},
        ),
    ]
