# Generated by Django 5.2.4 on 2025-07-19 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0005_movie_country_movie_extra_data_alter_movie_year_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="movie",
            old_name="year",
            new_name="release_year",
        ),
        migrations.AlterUniqueTogether(
            name="movie",
            unique_together={("title", "country", "release_year")},
        ),
    ]
